### PR TITLE
moment.zone() is depricated

### PR DESCRIPTION
**Pull request by Rudolph-Miller**

### CODE REVIEW

**Comment by skratchdot** [comment]
I've been updating that file w/ exactly what's upstream, so hopefully we can get the same change there (or else I'll lose this change next time I update w/ upstream): https://github.com/dangrossman/bootstrap-daterangepicker

The way I update is by running:
```bash
gulp download
```

So we'll either want to make the same change next time `gulp download` is ran, or update the gulp script to make this same change.

Thanks for the PR though.  I'm pulling it in now...

**Comment by skratchdot** [comment]
This should fix #8, but we'll want to make the same change upstream if possible: https://github.com/dangrossman/bootstrap-daterangepicker

**Comment by Rudolph-Miller** [comment]
I see the system of this repo.
You should do this with npm to depend on other lib.
Then it will be automatically updated, and you will have no task to fix bugs in upstream lib.

**Comment by skratchdot** [comment]
@Rudolph-Miller - true.  When I created this module, the upstream didn't have a package.json in the repo, so I would have had to maintain a fork, etc. They also didn't have node style / commonjs support working at first.  It looks like they have a package.json now (added back in November), so I can probably just start using npm now.  Good point.

**Comment by Rudolph-Miller** [comment]
I see.
Good decision.

**Pull request merged**
